language: ruby
rvm:
- 2.3.1
services:
  - postgresql
install:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - ./bin/setup
script:
  - ./bin/rake
  - ./bin/codeclimate-test-reporter
addons:
  postgresql: "9.4"